name: asp
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - tqdm
  - numpy
  - nvidia-apex
  - scipy
  - python=3.8
  - pytorch
  - pytorch-cuda=11.7
  - huggingface_hub
  - huggingface_accelerate
  - transformers=4.23.1
  - pip:
    - truecase
    - pyhocon
    - sentencepiece
