name: asp
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - tqdm
  - numpy
  - scipy
  - python
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - huggingface_hub
  - huggingface_accelerate
  - timm
  - transformers=4.27.4
  - tokenizers=0.13.0
  - pip:
    - truecase
    - pyhocon
    - sentencepiece
