name: asp
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - pip
  - tqdm
  - numpy
  - scipy
  - python
  - pytorch
  - pytorch-cuda
  - huggingface_hub
  - huggingface_accelerate
  - transformers
  - tokenizers
  - pip:
    - truecase
    - pyhocon
    - sentencepiece
